### ISSUE TITLE
runtime: traceback doesn't work correctly

### ISSUE THREAD

**Issue by 4ad** [4ad/go.arm64#115]
Perhaps it has something to do with 16-byte aligned stacks.

```
: xgene:linux_arm64; /home/aram/go/bin/linux_arm64/go
fatal error: bad map state

goroutine 1 [running, locked to thread]:
runtime.throw(0x0, 0x1)
    /home/aram/go/src/runtime/panic.go:508 +0xf0 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
runtime.evacuate(0x0, 0x1, 0x4208036198)
    /home/aram/go/src/runtime/hashmap.go:799 +0x530 fp=0x420801a110 sp=0x420801a110
...additional frames elided...

goroutine 2 [runnable]:
runtime.forcegchelper()
    /home/aram/go/src/runtime/proc.go:111
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:897 +0x4

goroutine 3 [runnable]:
runtime.backgroundgc()
    /home/aram/go/src/runtime/mgc0.go:63
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:897 +0x4
: xgene:linux_arm64; 
```

**Comment by mwhudson** [comment]
Is this something more than the fact that we don't actually use a frame pointer?

**Comment by minux** [comment]
No. The runtime doesn't need frame pointer to do traceback.

Once we have spadj tracking (#114), this is fixed. See my latest email.

**Comment by mwhudson** [comment]
Ah ok, sorry for the noise.

**Comment by minux** [comment]
This has been fixed.
