### ISSUE TITLE
runtime: unknown caller pc

### ISSUE THREAD

**Issue by 4ad** [4ad/go.arm64#132]
```
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x343910, 0x11)
    /home/aram/go/src/runtime/panic.go:508 +0xf0 fp=0x7fd7ec8fe0 sp=0x7fd7ec8fb0
runtime.gentraceback(0x11a1b0, 0x420ab14ee0, 0x181548, 0x4208000120, 0x0, 0x0, 0x7fffffff, 0x42b808, 0x7fd7ec9208, 0x0, ...)
    /home/aram/go/src/runtime/traceback.go:224 +0x1228 fp=0x7fd7ec9160 sp=0x7fd7ec8fe0
runtime.copystack(0x4208000120, 0x4000)
    /home/aram/go/src/runtime/stack1.go:552 +0x23c fp=0x7fd7ec9240 sp=0x7fd7ec9160
runtime.shrinkstack(0x4208000120)
    /home/aram/go/src/runtime/stack1.go:805 +0x1c8 fp=0x7fd7ec9280 sp=0x7fd7ec9240
runtime.markroot(0x4208010000, 0x7f00000005)
    /home/aram/go/src/runtime/mgc.go:571 +0x200 fp=0x7fd7ec9300 sp=0x7fd7ec9280
runtime.parfordo(0x4208010000)
    /home/aram/go/src/runtime/parfor.go:69 +0x1f4 fp=0x7fd7ec93a0 sp=0x7fd7ec9300
runtime.gc(0xe778ca2960, 0x400000000)
    /home/aram/go/src/runtime/mgc.go:1536 +0x3ec fp=0x7fd7ec9510 sp=0x7fd7ec93a0
runtime.gc_m(0xe778ca2960, 0x7f8b448500)
    /home/aram/go/src/runtime/mgc.go:1339 +0xbc fp=0x7fd7ec9540 sp=0x7fd7ec9510
runtime.func·006()
    /home/aram/go/src/runtime/malloc.go:416 +0x54 fp=0x7fd7ec9570 sp=0x7fd7ec9540
runtime.systemstack(0x4ccac0)
    /home/aram/go/src/runtime/asm_arm64.s:155 +0x80 fp=0x7fd7ec9580 sp=0x7fd7ec9570
runtime.mstart()
    /home/aram/go/src/runtime/proc1.go:714 fp=0x7fd7ec9580 sp=0x7fd7ec9580

goroutine 2 [garbage collection]:
runtime.systemstack_switch()
    /home/aram/go/src/runtime/asm_arm64.s:105 +0x8 fp=0x420801a6c0 sp=0x420801a6b0
runtime.gcwork(0x1)
    /home/aram/go/src/runtime/malloc.go:417 +0x364 fp=0x420801a760 sp=0x420801a6c0
runtime.gogc(0x1)
    /home/aram/go/src/runtime/malloc.go:347 +0x180 fp=0x420801a7a0 sp=0x420801a760
runtime.forcegchelper()
    /home/aram/go/src/runtime/proc.go:125 +0x17c fp=0x420801a7d0 sp=0x420801a7a0
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:887 +0x4 fp=0x420801a7d0 sp=0x420801a7d0
created by runtime.init·4
    /home/aram/go/src/runtime/proc.go:108 +0x3c

goroutine 1 [copystack]:
rsc.io/c2go/cc.(*SyntaxInfo).GetSpan(0x4207cd8bfd, 0x490489, 0x8484888848010000, 0x4448444884444884, 0x4884848488884849, 0x4849444844488444, 0x8444488484848888, 0x8888484944484448, 0x4448844448848484)
    /home/aram/src/rsc.io/c2go/cc/lex.go:40 fp=0x420ab14ee0 sp=0x420ab14ee0
rsc.io/c2go/cc.(*Decl).GetSpan(0x8484888848010000, 0x4448444884444884, 0x4884848488884849, 0x4849444844488444, 0x8444488484848888, 0x8888484944484448, 0x4448844448848484, 0x0, 0x0)
    <autogenerated>:15 +0x38 fp=0x420ab14ef0 sp=0x420ab14ee0
rsc.io/c2go/cc.byStart.Less(0x420b4c2000, 0x2b859, 0x2d600, 0x0, 0x570b, 0x100000001)
    /home/aram/src/rsc.io/c2go/cc/lex.go:706 +0xa8 fp=0x420ab15030 sp=0x420ab14ef0

goroutine 3 [Concurrent GC wait]:
runtime.gopark(0x42ba40, 0x4cc820, 0x338810, 0x12)
    /home/aram/go/src/runtime/proc.go:151 +0x190 fp=0x420801af70 sp=0x420801af30
runtime.goparkunlock(0x4cc820, 0x338810, 0x12)
    /home/aram/go/src/runtime/proc.go:157 +0x68 fp=0x420801afa0 sp=0x420801af70
runtime.backgroundgc()
    /home/aram/go/src/runtime/mgc0.go:70 +0xc8 fp=0x420801afd0 sp=0x420801afa0
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:887 +0x4 fp=0x420801afd0 sp=0x420801afd0
created by runtime.gogc
    /home/aram/go/src/runtime/malloc.go:340 +0x12c

goroutine 4 [finalizer wait, 2 minutes]:
runtime.gopark(0x42ba40, 0x4dd508, 0x32e570, 0xe)
    /home/aram/go/src/runtime/proc.go:151 +0x190 fp=0x420801b6e0 sp=0x420801b6a0
runtime.goparkunlock(0x4dd508, 0x32e570, 0xe)
    /home/aram/go/src/runtime/proc.go:157 +0x68 fp=0x420801b710 sp=0x420801b6e0
runtime.runfinq()
    /home/aram/go/src/runtime/mfinal.go:130 +0xec fp=0x420801b7d0 sp=0x420801b710
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:887 +0x4 fp=0x420801b7d0 sp=0x420801b7d0
created by runtime.createfing
    /home/aram/go/src/runtime/mfinal.go:110 +0x8c

goroutine 5 [chan send, 2 minutes]:
runtime.gopark(0x42ba40, 0x420805e178, 0x32d950, 0x9)
    /home/aram/go/src/runtime/proc.go:151 +0x190 fp=0x420801be70 sp=0x420801be30
runtime.goparkunlock(0x420805e178, 0x32d950, 0x9)
    /home/aram/go/src/runtime/proc.go:157 +0x68 fp=0x420801bea0 sp=0x420801be70
runtime.chansend(0x29b5c0, 0x420805e120, 0x420801bfc8, 0x1, 0x61908, 0x0)
    /home/aram/go/src/runtime/chan.go:181 +0x57c fp=0x420801bf50 sp=0x420801bea0
runtime.chansend1(0x29b5c0, 0x420805e120, 0x420801bfc8)
    /home/aram/go/src/runtime/chan.go:75 +0x48 fp=0x420801bf90 sp=0x420801bf50
main.func·011()
    /home/aram/src/rsc.io/c2go/syntax.go:311 +0x58 fp=0x420801bfd0 sp=0x420801bf90
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:887 +0x4 fp=0x420801bfd0 sp=0x420801bfd0
created by main.init·1
    /home/aram/src/rsc.io/c2go/syntax.go:313 +0x3c

goroutine 6 [GC sweep wait]:
runtime.gopark(0x42ba40, 0x4dd510, 0x328d50, 0xd)
    /home/aram/go/src/runtime/proc.go:151 +0x190 fp=0x420801df60 sp=0x420801df20
runtime.goparkunlock(0x4dd510, 0x328d50, 0xd)
    /home/aram/go/src/runtime/proc.go:157 +0x68 fp=0x420801df90 sp=0x420801df60
runtime.bgsweep()
    /home/aram/go/src/runtime/mgc0.go:91 +0x150 fp=0x420801dfd0 sp=0x420801df90
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:887 +0x4 fp=0x420801dfd0 sp=0x420801dfd0
created by runtime.gc
    /home/aram/go/src/runtime/mgc.go:1632 +0x1300
```

**Comment by minux** [comment]
The arguments to rsc.io/c2go/cc.(*SyntaxInfo).GetSpan looks funny, is that
because a stack corruption problem?

**Comment by 4ad** [comment]
You can also see them in the TestStackOverflow failure.

**Comment by minux** [comment]
liblink retjmp issue. I think 9g is also affected, I will file a upstream issue.

```
package main

type T1 struct {
        X int
}

type R struct {
        pad [128]byte
}

func (t *T1) M(y int) R {
        println("T1.M", t.X, y)
        panic(t)
}

type T2 struct {
        T1
        Z int
}

type I interface {
        M(int) R
}

func smash() {
        var x [128]int
        for i := range x {
                x[i] = 0xdead
        }
}

func main() {
        // use interface to force it to go through (*T2).M
        var t I = &T2{T1: T1{X: 42}, Z: 43}
        smash()
        t.M(44)
}
```
