### ISSUE TITLE
runtime: frame runtime.systemstack_switch untyped locals

### ISSUE THREAD

**Issue by 4ad** [4ad/go.arm64#146]
Didn't we solve this once already?

```
/home/aram/go/bin/linux_arm64/go list cmd
runtime: frame runtime.systemstack_switch untyped locals 0x420801c720+0x10
fatal error: missing stackmap

runtime stack:
runtime.throw(0x79c5b0, 0x10)
    /home/aram/go/src/runtime/panic.go:511 +0x108
runtime.scanframeworker(0x7fe846a9e0, 0x0, 0x7fe846aaa0)
    /home/aram/go/src/runtime/mgcmark.go:303 +0xc24
runtime.scanstack.func1(0x7fe846a9e0, 0x0, 0x7f00000001)
    /home/aram/go/src/runtime/mgcmark.go:256 +0x50
runtime.gentraceback(0x15b978, 0x420801c720, 0x0, 0x42080bd200, 0x0, 0x0, 0x7fffffff, 0x7fe846aac0, 0x0, 0x0, ...)
    /home/aram/go/src/runtime/traceback.go:298 +0xabc
runtime.scanstack(0x42080bd200)
    /home/aram/go/src/runtime/mgcmark.go:259 +0x3a4
runtime.gcphasework(0x42080bd200)
    /home/aram/go/src/runtime/mgcmark.go:209 +0x108
runtime.stopg(0x42080bd200, 0x4)
    /home/aram/go/src/runtime/proc1.go:395 +0x108
runtime.markroot(0x4208010000, 0xa)
    /home/aram/go/src/runtime/mgcmark.go:134 +0x290
runtime.parfordo(0x4208010000)
    /home/aram/go/src/runtime/parfor.go:95 +0x218
runtime.gcscan_m()
    /home/aram/go/src/runtime/mgcmark.go:37 +0x150
runtime.gc.func1()
    /home/aram/go/src/runtime/mgc.go:320 +0x54
runtime.systemstack(0x99cb90)
    /home/aram/go/src/runtime/asm_arm64.s:155 +0x80
runtime.mstart()
    /home/aram/go/src/runtime/proc1.go:682

goroutine 7 [garbage collection scan]:
runtime.systemstack_switch()
    /home/aram/go/src/runtime/asm_arm64.s:104 +0x8 fp=0x420801c730 sp=0x420801c720
runtime.gc(0x0)
    /home/aram/go/src/runtime/mgc.go:339 +0x17c fp=0x420801c7a0 sp=0x420801c730
runtime.backgroundgc()
    /home/aram/go/src/runtime/mgc.go:281 +0x5c fp=0x420801c7d0 sp=0x420801c7a0
runtime.goexit()
    /home/aram/go/src/runtime/asm_arm64.s:887 +0x4 fp=0x420801c7d0 sp=0x420801c7d0
created by runtime.startGC
    /home/aram/go/src/runtime/mgc.go:260 +0x140

goroutine 1 [runnable]:
go/parser.(*parser).consumeCommentGroup(0x4208469b00, 0x1, 0x0, 0x3)
    /home/aram/go/src/go/parser/parser.go:288 +0x2f8
go/parser.(*parser).next(0x4208469b00)
    /home/aram/go/src/go/parser/parser.go:333 +0x198
go/parser.(*parser).init(0x4208469b00, 0x4208464e80, 0x42084a67b0, 0x2a, 0x4208499300, 0xcb, 0x100, 0x6)
    /home/aram/go/src/go/parser/parser.go:78 +0x208
go/parser.ParseFile(0x4208464e80, 0x42084a67b0, 0x2a, 0x60a340, 0x42084a3420, 0x6, 0x0, 0x0, 0x0)
    /home/aram/go/src/go/parser/interface.go:113 +0x234
go/build.(*Context).Import(0x99c960, 0x744530, 0x1, 0x420846df80, 0x21, 0x0, 0x42083ce2ff, 0x0, 0x0)
    /home/aram/go/src/go/build/build.go:670 +0x3054
go/build.(*Context).ImportDir(0x99c960, 0x420846df80, 0x21, 0x0, 0x8492c0, 0x0, 0x0)
    /home/aram/go/src/go/build/build.go:407 +0xb4
main.matchPackages.func3(0x420846df80, 0x21, 0x7f88965ca0, 0x4208474820, 0x0, 0x0, 0x0, 0x0)
    /home/aram/go/src/cmd/go/main.go:555 +0xb04
path/filepath.walk(0x420846df80, 0x21, 0x7f88965ca0, 0x4208474820, 0x420810f200, 0x0, 0x0)
    /home/aram/go/src/path/filepath/path.go:344 +0xc0
path/filepath.walk(0x42083d6f60, 0x1e, 0x7f88965ca0, 0x42083cd3b0, 0x420810f200, 0x0, 0x0)
    /home/aram/go/src/path/filepath/path.go:369 +0xa08
path/filepath.walk(0x4208112a80, 0x16, 0x7f88965ca0, 0x420805bcc0, 0x420810f200, 0x0, 0x0)
    /home/aram/go/src/path/filepath/path.go:369 +0xa08
path/filepath.Walk(0x4208112a80, 0x16, 0x420810f200, 0x0, 0x0)
    /home/aram/go/src/path/filepath/path.go:391 +0x248
main.matchPackages(0x7fe846b948, 0x3, 0x0, 0x0, 0x0)
    /home/aram/go/src/cmd/go/main.go:563 +0x7ec
main.allPackages(0x7fe846b948, 0x3, 0x0, 0x0, 0x0)
    /home/aram/go/src/cmd/go/main.go:495 +0x70
main.importPathsNoDotExpansion(0x420800a020, 0x1, 0x1, 0x0, 0x0, 0x0)
    /home/aram/go/src/cmd/go/main.go:326 +0x63c
main.importPaths(0x420800a020, 0x1, 0x1, 0x0, 0x0, 0x0)
    /home/aram/go/src/cmd/go/main.go:336 +0x7c
main.packagesAndErrors(0x420800a020, 0x1, 0x1, 0x0, 0x0, 0x0)
    /home/aram/go/src/cmd/go/pkg.go:919 +0x380
main.packages(0x420800a020, 0x1, 0x1, 0x0, 0x0, 0x0)
    /home/aram/go/src/cmd/go/pkg.go:900 +0x90
main.runList(0x997860, 0x420800a020, 0x1, 0x1)
    /home/aram/go/src/cmd/go/list.go:175 +0x360
main.main()
    /home/aram/go/src/cmd/go/main.go:175 +0xd84

goroutine 4 [syscall]:
os/signal.loop()
    /home/aram/go/src/os/signal/signal_unix.go:22 +0x28
created by os/signal.init.1
    /home/aram/go/src/os/signal/signal_unix.go:28 +0x48
```

**Comment by minux** [comment]
Fixed.
