### ISSUE TITLE
cmd/7l: bus error writing dwarf data

### ISSUE THREAD

**Issue by davecheney** [4ad/go.arm64#29]
```
rugby(~/go.arm64/src) % ../pkg/tool/linux_arm64/7g ~/src/x.go
rugby(~/go.arm64/src) % ll x.7
-rw-r--r-- 1 dfc warthogs 1420 Jan  8 00:53 x.7
rugby(~/go.arm64/src) % ../pkg/tool/linux_arm64/7l x.7
Segmentation fault (core dumped)
rugby(~/go.arm64/src) % gdb --args ../pkg/tool/linux_arm64/7l x.7
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../pkg/tool/linux_arm64/7l...done.
(gdb) r
Starting program: /home/dfc/go.arm64/pkg/tool/linux_arm64/7l x.7

Program received signal SIGSEGV, Segmentation fault.
writelines () at /home/dfc/go.arm64/src/cmd/7l/../ld/dwarf.c:1564
1564            newattr(dwinfo, DW_AT_low_pc, DW_CLS_ADDRESS, s->value, (char*)s);
(gdb) bt
#0  writelines () at /home/dfc/go.arm64/src/cmd/7l/../ld/dwarf.c:1564
#1  0x0000000000408d3c in dwarfemitdebugsections () at /home/dfc/go.arm64/src/cmd/7l/../ld/dwarf.c:2077
#2  0x000000000041a36c in asmb () at /home/dfc/go.arm64/src/cmd/7l/asm.c:251
#3  0x0000000000418d0c in p9main (argc=1, argv=0x7ffffff560) at /home/dfc/go.arm64/src/cmd/7l/../ld/pobj.c:195
#4  0x0000000000401cb4 in main (argc=<optimized out>, argv=<optimized out>) at /home/dfc/go.arm64/src/lib9/main.c:57
```

**Comment by 4ad** [comment]
Make sure all sections are non empty.

**Comment by 4ad** [comment]
Works now.
